LICENSE = "MIT"
LIC_FILES_CHKSUM = "file://${COMMON_LICENSE_DIR}/MIT;md5=0835ade698e0bcf8506ecda2f7b4f302"

RDEPENDS:packagegroup-rdk-ccsp-broadband:append = " ccsp-dhcp-mgr"
RDEPENDS:packagegroup-rdk-ccsp-broadband:append = " ccsp-epon-agent"
RDEPENDS:packagegroup-rdk-ccsp-broadband:append = " ccsp-xconf"
RDEPENDS:packagegroup-rdk-ccsp-broadband:append = " dcmjsonparser"
RDEPENDS:packagegroup-rdk-ccsp-broadband:append = " memstress"
RDEPENDS:packagegroup-rdk-ccsp-broadband:append = " mesh-agent"
RDEPENDS:packagegroup-rdk-ccsp-broadband:append = " notify-comp"
RDEPENDS:packagegroup-rdk-ccsp-broadband:append = " harvester"
RDEPENDS:packagegroup-rdk-ccsp-broadband:append = " ovs-agent"
RDEPENDS:packagegroup-rdk-ccsp-broadband:append = " ${@bb.utils.contains('DISTRO_FEATURES', 'rdkb_power_manager', 'powermgr', '', d)}"
RDEPENDS:packagegroup-rdk-ccsp-broadband:append = " ${@bb.utils.contains('DISTRO_FEATURES', 'rdkb_wan_manager', 'ipoe-health-check', '', d)}"
RDEPENDS:packagegroup-rdk-ccsp-broadband:append = " json-hal-lib"
RDEPENDS:packagegroup-rdk-ccsp-broadband:append = " ${@bb.utils.contains('DISTRO_FEATURES', 'rdkb_gpon_manager', 'rdkgponmanager', '', d)}"
RDEPENDS:packagegroup-rdk-ccsp-broadband:append = " ${@bb.utils.contains('DISTRO_FEATURES', 'rdkb_xdsl_ppp_manager', 'rdkxdslmanager', '', d)}"
RDEPENDS:packagegroup-rdk-ccsp-broadband:append = " ${@bb.utils.contains('DISTRO_FEATURES', 'rdkb_wan_manager', 'rdk-wanmanager', '', d)}"
RDEPENDS:packagegroup-rdk-ccsp-broadband:append = " ${@bb.utils.contains('DISTRO_FEATURES', 'rdkb_voice_manager_dmltr104_v2', 'rdktelcovoicemanager', '', d)}"
RDEPENDS:packagegroup-rdk-ccsp-broadband:append = " rdk-vlanmanager"
RDEPENDS:packagegroup-rdk-ccsp-broadband:append = " ${@bb.utils.contains('DISTRO_FEATURES', 'rdkb_xdsl_ppp_manager', 'rdk-ppp-manager', '', d)}"
RDEPENDS:packagegroup-rdk-ccsp-broadband:append = " rdk-fwupgrade-manager"
RDEPENDS:packagegroup-rdk-ccsp-broadband:append = " ${@bb.utils.contains('DISTRO_FEATURES', 'easymesh-controller', 'rdk-easymesh-controller', '', d)}"
RDEPENDS:packagegroup-rdk-ccsp-broadband:append = " rdk-wifi-hal"
